### ISSUE TITLE
Compare button while in image overlay setting

### ISSUE THREAD

**Issue by addonify** [addonify/addonify-compare-products#10]
- Change the `div` class `addonify-qvm-overlay-button` to `addonify-compare-overlay-buttom`. 
- Once we have multiple buttons in image overlay setting one button may overlap others or create a problem. How about we provide an option to let the user change position. How about allowing them to control the position `**top, left, bottom, right**`?

**Comment by sonill** [comment]
cannot find ".addonify-qvm-overlay-button" css class anywhere. I think it is used in "quick view" plugin.
