### ISSUE TITLE
Invalid security token.

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-compare-products#101]
👉 Describe the Bug:

Add to compare is not working. Upon checking the console I noticed that we have the following response for ajax calls.  

`{"success":false,"message":"Invalid security token."}` 

This issue occurred while being cached. I have attached the screenshots. 

👉 Screenshots:

![Screenshot from 2022-11-10 21-03-33](https://user-images.githubusercontent.com/21140404/201134555-1739c0cf-4dd5-4be0-95dc-ce6a41b26552.png)

![Screenshot from 2022-11-10 21-04-36](https://user-images.githubusercontent.com/21140404/201134575-9800e0b8-e2da-49b0-94b1-e33483d530d7.png)

**Comment by Asok17** [comment]
- Commit, https://github.com/addonify/addonify-compare-products/pull/102, has the updated codes. The issue was created by, array_key_exists() function.
