### ISSUE TITLE
Compare button on product single

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-compare-products#185]
Requested by Leonidas on [support forum](https://wordpress.org/support/topic/additional-features-21/).

- [x] Compare button on product single.

**Comment by PalashSengupta92** [comment]
How to add the compare button on the product details page? Is there any shortcode available?

**Comment by Asok17** [comment]
Hi @PalashSengupta92

We'll be rolling out an update with the feature within 2-3 days. Please wait patiently.

**Comment by Asok17** [comment]
Closing issue. Feature release in the version 1.1.11.
