### ISSUE TITLE
Can't remove compare footer item

### ISSUE THREAD

**Issue by addonify** [addonify/addonify-compare-products#9]
Add a few products to compare them. Reload a page. Now you will notice a js error in console. Same time you will also notice the 1st product image as broken in compare footer. All other products in compare footer are dismissable but not the 1st.

**Comment by sonill** [comment]
is it on popup or page? I cannot replicate the error.

**Comment by h1dd3nsn1p3r** [comment]
@sonill Compare footer bar (bottom bar/Black bar at bottom)
